### ISSUE TITLE
library "ssh.dll" not found

### ISSUE THREAD

**Issue by jmnicolas90** [insinfo/libssh_binding#1]
Hello,

I tried to use this library in Dart and Flutter but the code throws an exception when I instantiate LibsshWrapper.
I'm running it on Ubuntu 21.04 and Dart & Flutter beta channel.

On the Dart project (VS Code) I have this error:
> ArgumentError (Invalid argument(s): Failed to load dynamic library 'ssh.dll': ssh.dll: cannot open shared object file: No such file or directory)

On Flutter (Android Studio):
> Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'ssh.dll': dlopen failed: library "ssh.dll" not found

Full code (it breaks on the first line):

```
import 'package:libssh_binding/libssh_binding.dart';

void main(List<String> arguments) async {
  final libssh = LibsshWrapper('192.168.1.43',
      username: '***', password: '***', port: 22, verbosity: true);

  libssh.connect();

  await libssh.scpDownloadFileTo(
      '/media/***/data4t/tmp/test.jpg', '/media/***/ssd2/test.jpg');

  libssh.disconnect();
  libssh.dispose();
}
```

Thank you.

**Comment by insinfo** [comment]
@jmnicolas90 
you have to install libssh, and pass the path, see the example below, tested on Ubuntu 20

##### linux (Debin/Ubuntu)

```
# install dart 2.14
sudo apt-get update
sudo apt-get install apt-transport-https
sudo sh -c 'wget -qO- https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -'
sudo sh -c 'wget -qO- https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list'
sudo apt-get update
sudo apt-get install dart=2.14*

# install libssh
sudo apt show libssh-4
sudo apt install libssh-4
# check
ldconfig -p | grep libssh
/lib/x86_64-linux-gnu/libssh.so.4
libssh.so.4
```


```dart
void main() async {
  var libraryPath = path.join('/lib/x86_64-linux-gnu/', 'libssh.so.4');
  print('libraryPath $libraryPath');
  final dll = DynamicLibrary.open(libraryPath);

  final libssh = LibsshWrapper('192.168.3.4',
      inDll: dll,
      username: 'isaque',
      password: 'Ins257257',
      port: 22,
      verbosity: true);
  libssh.connect();
  final start = DateTime.now();

 
  await libssh.scpDownloadDirectory('/var/www/html/portalPmro',
      path.join(Directory.current.path, 'download'));
  
  print('\r\n${DateTime.now().difference(start)}');
  libssh.dispose();
  exit(0);
}

```

**Comment by insinfo** [comment]
if you want to compile libssh for android see this link [Compiling libssh for Android](https://egorovandreyrm.com/compiling-libssh-for-android-with-boringssl/)
if you need it for ios see this link [libssh2 for ios,](https://github.com/Frugghi/iSSH2) it's not for libssh, it's for libssh2 but possibly the hints should be for libssh too

**Comment by jmnicolas90** [comment]
> @jmnicolas90 you have to install libssh, and pass the path, see the example below, tested on Ubuntu 20

@insinfo I added the path to libssh, it now works, thank you very much.
